import { getDefaultClassNames } from "./getDefaultClassNames";

test("should return the default classnames", () => {
	expect(getDefaultClassNames()).toStrictEqual({
		button_next: "rdp-button_next",
		button_previous: "rdp-button_previous",
		caption_after_enter: "rdp-caption_after_enter",
		caption_after_exit: "rdp-caption_after_exit",
		caption_before_enter: "rdp-caption_before_enter",
		caption_before_exit: "rdp-caption_before_exit",
		caption_label: "rdp-caption_label",
		chevron: "rdp-chevron",
		day: "rdp-day",
		day_button: "rdp-day_button",
		disabled: "rdp-disabled",
		dropdown: "rdp-dropdown",
		dropdown_root: "rdp-dropdown_root",
		dropdowns: "rdp-dropdowns",
		focused: "rdp-focused",
		footer: "rdp-footer",
		hidden: "rdp-hidden",
		month: "rdp-month",
		month_caption: "rdp-month_caption",
		month_grid: "rdp-month_grid",
		months: "rdp-months",
		months_dropdown: "rdp-months_dropdown",
		nav: "rdp-nav",
		outside: "rdp-outside",
		range_end: "rdp-range_end",
		range_middle: "rdp-range_middle",
		range_start: "rdp-range_start",
		root: "rdp-root",
		selected: "rdp-selected",
		today: "rdp-today",
		week: "rdp-week",
		week_number: "rdp-week_number",
		week_number_header: "rdp-week_number_header",
		weekday: "rdp-weekday",
		weekdays: "rdp-weekdays",
		weeks: "rdp-weeks",
		weeks_after_enter: "rdp-weeks_after_enter",
		weeks_after_exit: "rdp-weeks_after_exit",
		weeks_before_enter: "rdp-weeks_before_enter",
		weeks_before_exit: "rdp-weeks_before_exit",
		years_dropdown: "rdp-years_dropdown",
	});
});
